# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools.restart.customizing-the-classload
#https://stackoverflow.com/questions/48502933/could-not-set-field-value-by-reflection-spring-boot-devtools
#restart.include.common-code=/common-code-1.0.2.jar
#restart.include.common-code=/common-code-(.*).jar

#Note: If the jar version will change you can use regex, something like --> /common-code-(.*).jar
#<!--支持热部署-->
#热部署不支持field set 方法
#<dependency>
#<groupId>org.springframework.boot</groupId>
#<artifactId>spring-boot-devtools</artifactId>
#</dependency>

